container:
  image: node:latest

task:
  name: Test
  env:
    GITHUB_TOKEN: $CIRRUS_REPO_CLONE_TOKEN
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  build_script: npm run build
  test_script: npm test
