name: 'Branch Guard'
description: 'Guards branches from merges when'
author: 'Cirrus Labs'
inputs:
  appsToCheck:
    description: 'Comma separated list of App names to check. If empty, all Apps will be checked.'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
