name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      run: npm ci
    - name: Test
      run: npm run all
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
